name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  gotest:
    name: Test Backend
    runs-on: ubuntu-latest
    steps:
    - name: Valid yaml
      run: echo hello
